image: node:9.11.1
stages:
  - build

pages build job:
  stage: build
  cache:
    paths:
    - node_modules/

  script:
   - npm ci
   - npm run build 
 
  artifacts:
    paths:
    - public
  only:
  - master