stages:
  - build

pages build job:
  stage: build
  cache:
    paths:
    - node_modules/

  script:
   - npm ci
   - npm run build

  artifacts:
    paths:
    - docs/.vuepress/dist

  only:
  - master