stages:
  - build

pages build job:
  stage: build
  cache:
    paths:
    - node_modules/

  script:
  #- /usr/bin/yarn install
  #- /usr/bin/yarn run build
   - echo "just ok for me!"

  artifacts:
    paths:
    - .vuepress/dist
  
  only:
  - master