image: docker.ccbjb.com.cn/node:latest
#image: node:latest
pages:
  cache:
    paths:
    - node_modules/

  script:
   - yarn install
   - yarn run build 
 
  artifacts:
    paths:
    - public
  only:
  - master