image: ${LOCAL_REGISTRY}/node:latest

pages:
  cache:
    key: "$CI_JOB_STAGE"
    paths:
    - node_modules/

  script:
   - yarn install
   - yarn run build 
 
  artifacts:
    paths:
    - public
  only:
  - master

  
=======
  - master
>>>>>>> 8a8c61f193633035ec3417b0eddd79ce4ac08191
