image: node:latest
stages:
  - build

pages build job:
  stage: build
  cache:
    paths:
    - node_modules/

  script:
   - yarn install
   - yarn run build 
 
  artifacts:
    paths:
    - public
  only:
  - master