stages:
  - build

pages build job:
  stage: build
  cache:
    paths:
    - node_modules/

  script:
   - npm ci
   - npm run build
   - echo "just ok for me!"

  artifacts:
    paths:
    - .vuepress/dist
  
  only:
  - master