# travis 网络有些不稳定，build经常失败。
# 最后deploy的时候，总找不到public目录。deploy失败。

language: node_js
node_js:
  - "10"
install:
  - yarn install # npm ci
  #- npm install -g vuepress
script:
  - yarn run build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: false
  #local_dir: /public
  local_dir: /xenial
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master